### PR TITLE
upgrade triangle.net to beta4

### PR DESCRIPTION
**Pull request by brnkhy**
@BergWerkGIS can you check this? I updated the triangle.net to beta4 for ease of use (while cutting polygons) but I'm not sure if it works with your UWP changes.

### CODE REVIEW

**Comment by wilhelmberg** [comment]
@brnkhy out of curiosity: where did you get `beta4`?
https://triangle.codeplex.com/ looks pretty abandoned.

Please add the zip or a link to the source, like the previous zip from CodePlex here: https://github.com/mapbox/triangle.net-uwp/blob/master/Triangle-Source-2013-06-18.zip

**Comment by wilhelmberg** [comment]
@brnkhy lot of `missing file` errors for `NetStandard` and `UWP`:

```
1>------ Rebuild All started: Project: TriangleUWP, Configuration: Debug Any CPU ------
1>CSC : error CS2001: Source file 'C:\mb\triangle.net-uwp\Triangle.NET\TriangleUWP\..\Triangle\Algorithm\Dwyer.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\mb\triangle.net-uwp\Triangle.NET\TriangleUWP\..\Triangle\Carver.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\mb\triangle.net-uwp\Triangle.NET\TriangleUWP\..\Triangle\Data\BadSubseg.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\mb\triangle.net-uwp\Triangle.NET\TriangleUWP\..\Triangle\Tools\BoundedVoronoi.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\mb\triangle.net-uwp\Triangle.NET\TriangleUWP\..\Triangle\Data\BadTriangle.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\mb\triangle.net-uwp\Triangle.NET\TriangleUWP\..\Triangle\Data\Osub.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\mb\triangle.net-uwp\Triangle.NET\TriangleUWP\..\Triangle\Data\Otri.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\mb\triangle.net-uwp\Triangle.NET\TriangleUWP\..\Triangle\Algorithm\Incremental.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\mb\triangle.net-uwp\Triangle.NET\TriangleUWP\..\Triangle\Data\Segment.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\mb\triangle.net-uwp\Triangle.NET\TriangleUWP\..\Triangle\Algorithm\ITriangulator.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\mb\triangle.net-uwp\Triangle.NET\TriangleUWP\..\Triangle\Data\Triangle.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\mb\triangle.net-uwp\Triangle.NET\TriangleUWP\..\Triangle\Algorithm\SweepLine.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\mb\triangle.net-uwp\Triangle.NET\TriangleUWP\..\Triangle\Data\Vertex.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\mb\triangle.net-uwp\Triangle.NET\TriangleUWP\..\Triangle\Log\ILog.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\mb\triangle.net-uwp\Triangle.NET\TriangleUWP\..\Triangle\Geometry\BoundingBox.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\mb\triangle.net-uwp\Triangle.NET\TriangleUWP\..\Triangle\BadTriQueue.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\mb\triangle.net-uwp\Triangle.NET\TriangleUWP\..\Triangle\Geometry\EdgeEnumerator.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\mb\triangle.net-uwp\Triangle.NET\TriangleUWP\..\Triangle\Log\ILogItem.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\mb\triangle.net-uwp\Triangle.NET\TriangleUWP\..\Triangle\Geometry\InputGeometry.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\mb\triangle.net-uwp\Triangle.NET\TriangleUWP\..\Triangle\Log\SimpleLog.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\mb\triangle.net-uwp\Triangle.NET\TriangleUWP\..\Triangle\Log\SimpleLogItem.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\mb\triangle.net-uwp\Triangle.NET\TriangleUWP\..\Triangle\Tools\IVoronoi.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\mb\triangle.net-uwp\Triangle.NET\TriangleUWP\..\Triangle\Tools\QuadTree.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\mb\triangle.net-uwp\Triangle.NET\TriangleUWP\..\Triangle\IO\DataReader.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\mb\triangle.net-uwp\Triangle.NET\TriangleUWP\..\Triangle\Tools\Voronoi.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\mb\triangle.net-uwp\Triangle.NET\TriangleUWP\..\Triangle\Tools\VoronoiRegion.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\mb\triangle.net-uwp\Triangle.NET\TriangleUWP\..\Triangle\IO\FileReader.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\mb\triangle.net-uwp\Triangle.NET\TriangleUWP\..\Triangle\IO\FileWriter.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\mb\triangle.net-uwp\Triangle.NET\TriangleUWP\..\Triangle\Tools\RegionIterator.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\mb\triangle.net-uwp\Triangle.NET\TriangleUWP\..\Triangle\IO\IGeometryFormat.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\mb\triangle.net-uwp\Triangle.NET\TriangleUWP\..\Triangle\Primitives.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\mb\triangle.net-uwp\Triangle.NET\TriangleUWP\..\Triangle\Quality.cs' could not be found.
1>CSC : error CS2001: Source file 'C:\mb\triangle.net-uwp\Triangle.NET\TriangleUWP\..\Triangle\Sampler.cs' could not be found.
```

----

It's easy to try for yourself:
* Open `Triangle.NET\Triangle.sln`
* Make sure that `Debug - Any CPU` is selected
* Right click on the project you want to build:
  * `Triangle` => Net35
  * `TriangleNetStandard (Portable)` => Portable Net Standard
  * `TriangleUWP (Universal Windows)` => UWP
* Resulting DLLs will be in
  * `Triangle.Net\bin\Debug\`
    * `Net35\`
    * `NetStandard13\`
    * `uap10\`

**Comment by brnkhy** [comment]
@BergWerkGIS it's actually in that codeplex repo but not in downloads section. If you get the source code, that's beta 4.

I don't understand the missing files thing. Those files aren't used in beta4 so obviously missing but who needs them in the first place?

**Comment by wilhelmberg** [comment]
>  it's actually in that codeplex repo but not in downloads section. If you get the source code, that's beta 4.

Ah, thanks for the clarification.
Could you put the downloaded source into a zip at the root of the repo (like the old one that's already there) - just a safe measure to be able to get back to the original if we need to.

Codeplex will be shutdown at the end of this year:
image

> I don't understand the missing files thing. Those files aren't used in beta4 so obviously missing but who needs them in the first place?

Obviously they have existed in `beta3`, that's why they are referenced.
Please update the `TriangleNetStandard` and `TriangleUWP` projects to reference the appropriate `beta4` files.

**Comment by brnkhy** [comment]
@BergWerkGIS OK thanks Willy. I think I won't rush this as I have some question marks in my head for this new version. I'll play with it a little before merging anything.

**Comment by david-rhodes** [comment]
@BergWerkGIS develop of `unity` repo is currently sitting on this branch. I think we're slightly confused about what we need to do to get this merged into master. Could you help us out, please?

**Comment by wilhelmberg** [comment]
@brnkhy wrt requested review: Haven't seen any tests. 
Are there some or do you see any sense in creating some?

As mentioned above (https://github.com/mapbox/triangle.net-uwp/pull/1#issuecomment-295233505 and https://github.com/mapbox/triangle.net-uwp/pull/1#issuecomment-295296372) could you please update the **`TriangleNetStandard`** and **`TriangleUWP`** projects to account for the changed files?

It's necessary that those build before we update `mapbox-unity-sdk`.
So we can make sure upfront that WindowsStore/Desktop/HoloLens Unity builds will most likely work and save same iterations going back and forth between the two repos.

Getting 33 `not found` errors with each project:
image

1. You could either go through them via Visual Studio (`Right click: Add -> Add existing item`).
**Please make sure to select `Add As Link` that we don't get duplicate files!**
image

2. Or work on the `csproj` files directly with a text editor. E.g.: fragment that needs some love for `TriangleUWP.csproj` would be this:
https://github.com/mapbox/triangle.net-uwp/blob/beta4upgrade/Triangle.NET/TriangleUWP/TriangleUWP.csproj#L110-L267

-----

@david-rhodes wrt bringing this into `mapbox-unity-sdk`:

Has this already been tested with Unity?
If yes, I think it's safe to directly update `develop` there.
If no, I think a separate branch to bring this in might be a good idea.

* merge here
* in `mapbox-unity-sdk`
  ```
  cd dependencies/triangle.net-uwp
  git checkout master
  git pull
  cd ../..
  git add dependencies/triangle.net-uwp
  git commit -m "updated triangle.net to beta4"
  git push
```

**Comment by david-rhodes** [comment]
@BergWerkGIS This has been tested in the Unity Editor (and develop is currently pointing to `beta4`. As you pointed out, it is important to maintain support for our existing platforms, moving forward. I just don't think we're used to maintaining separate projects (this bit me before, as Xamarin doesn't even allow me to manipulate the `uwp` project).

Maybe we can streamline/simplify this process in the future?

**Comment by wilhelmberg** [comment]
> This has been tested in the Unity Editor

Unfortunately: `Unity Editor != UWP`.
They expose different APIs.

>  this bit me before, as Xamarin doesn't even allow me to manipulate the uwp project.

Probably you need to install some additional components.
Don't know if this is even possible on Mac.
On Windows with Visual Studio there are additional installs necessary to build for `Universal Windows Platform (UWP)`.

@brnkhy aren't you on Windows too?
You should be able to `right click -> Build` on the respective projects to see the errors.


>  I just don't think we're used to maintaining separate projects
> Maybe we can streamline/simplify this process in the future?

Currently I don't have any idea, if/how this would work within a single project and cross platform.
Open for suggestions.

**Comment by wilhelmberg** [comment]
Trying to export current `mapbox-unity-sdk@develop` to `Windows Store` produces 14 errors related to `Triangle.Net`:

image

**Comment by brnkhy** [comment]
@BergWerkGIS I think the demos inside the library are broken, I fixed links and unloaded those project. I hope I did it right ><

**Review by wilhelmberg — APPROVED** [review]
Thanks @brnkhy 
Looking good now.

**Pull request merged**
